apiVersion: v1
kind: PersistentVolume
metadata:
 name: nfs-storage-pv
 labels:
   type: nfs
   app: pv
spec:
 capacity:
   storage: 1Gi
 accessModes:
    - ReadWriteMany
 persistentVolumeReclaimPolicy: Recycle
 nfs:
  path: /home/yang/images
  server: 192.168.198.128
  readOnly: false
