apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    name: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        name: jenkins
    spec:
      containers:
      - name: jenkins
        image: 192.168.26.46/onlineshop/jenkins:2.60.3
        ports:
        - containerPort: 8080
