server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/james_DUT_yang/SpringMVCTest/     # 配置git仓库的地址
          search-paths: tree/master/src/resources/config-repo       # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: drawnkid@gmail.com                               # git仓库的账号
          password: 3.1415926oschina                            # git仓库的密码
#        native:
#          fail-on-error: true
#          version: dev
